#debug: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:9080/orders
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123

logging:
  level:
    root: info
    org.hibernate.type: trace
    org.springframework: debug
